
/*
	Title:
		Even Fibonacci numbers

	Description:
		Each new term in the Fibonacci sequence is generated by adding the previous two terms.
		By starting with 1 and 2, the first 10 terms will be:

		                          1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
								  
		By considering the terms in the Fibonacci sequence whose values do not exceed four million,
		find the sum of the even-valued terms.

	Date:
		03-05-2020
*/


#include <iostream>


int main()
{
	int sum = 2;

	int previous_val = 1;
	int current_val = 2;
	int new_val;

	while (current_val < 4000000) {
		new_val = previous_val + current_val;
		previous_val = current_val;
		current_val = new_val;

		if (current_val % 2 == 0) sum += current_val;
	}

	std::cout << sum << '\n';

	return 0;
}